### ISSUE TITLE
The test code can not work on 32bit julia 

### ISSUE THREAD

**Issue by eddyzhang1986** [ETC-UA/LeafAreaIndex.jl#1]
The test code can not work on 32bit julia

**Comment by Ken-B** [comment]
Thanks for your message! Could you be more specific on which (line of) test would not work on 32bit? 

I'd be happy to adjust.

**Comment by eddyzhang1986** [comment]
Hi,
  Thank you for your reply ,

   I use juno IDE which the Official WebSite Provide , 

   more information for this problem:

   OS : Wiindows7 32bit ,
   IDE: juno32bit
   julia:32bit version v0.3.9
   error codes:

![cache_-2709273b7fbfe654](https://cloud.githubusercontent.com/assets/6470398/8019575/98a637fe-0c88-11e5-9044-d8c20d688082.jpg)

   By the way, I want to translate these codes to c#,can you give me more help?

   this project has given me a lot of help

   thanks a lot.

**Comment by Ken-B** [comment]
The error seems to come from the ArrayViews package. Do the tests pass for
that package on your machine? If not, could you file an issue with
ArrayViews.jl?

I only use the ArrayViews package for speed, although you could argue it is
not necessary during calibration as this will only need to be done once.
You could change that line to:

```
ρ²spiralind = sortperm(ϕsort[ind_prev:ρ²startind-1])
```

and similarly other occurances of ArrayViews in the code (although that
might affect the speed).

You are free to translate my code, but could I ask why you want to
translate it? Is there anything missing from this package or prevents you
to use this Julia package directly?

**Comment by eddyzhang1986** [comment]
Thanks for your answer ,Ken,
Let me try your method to solve this problem,
I translate  these codes because  I get used to  make website application with c#

Thank you.

**Comment by Ken-B** [comment]
Our website (https://icos.ua.ac.be) is also made with C# and communicates
with the Julia code through the database. See
https://github.com/ETC-UA/LAIscript for the Julia script.

Please let me know when your problem is solved so I can close this issue.
Thanks.

**Comment by eddyzhang1986** [comment]
This problem has been solved by your method.

 Thank you very much, Ken!

**Comment by eddyzhang1986** [comment]
Hi, Ken
I visit https://icos.ua.ac.be 
is it free?
seems can not regist account of this website.

**Comment by Ken-B** [comment]
At the moment the website's still in beta phase, so please use the contact form on the website to ask for access.

**Comment by eddyzhang1986** [comment]
OK,I got it
thanks.
